### ISSUE TITLE
La clase 3 de Docker no tiene la url seteada

### ISSUE THREAD

**Issue by saantiaguilera** [taller-de-programacion-2/taller-de-programacion-2.github.io#1]
La clase 3 de Docker en [el programa](https://taller-de-programacion-2.github.io/institucional/programa/) no tiene el link al ppt creado

PD: No quiero recursar solo quiero el link (?)

**Comment by abrden** [comment]
Por el momento, creo que [acá](https://github.com/mlafroce/mlafroce.github.io/tree/master/tutorials/es/docker-para-que) está todo lo que vimos Santi :grin:
